-- Run once in the Neon SQL Editor (as the owner role) to create the bets table.
-- Prereq: Neon Auth must be enabled on this project so that auth.user_id() is available.

CREATE TABLE bets (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          text        NOT NULL DEFAULT (auth.user_id()),
  site_key         text        NOT NULL,   -- 'fanduel' | 'caesars' | 'draftkings' | …
  external_bet_id  text        NOT NULL,
  placed_at        timestamptz,
  status           text,                   -- 'open' | 'won' | 'lost' | 'pushed' | 'void'
  stake            numeric(12,2),
  potential_payout numeric(12,2),
  selections       jsonb,
  raw              jsonb,
  scraped_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, site_key, external_bet_id)
);
